<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('country', function (Blueprint $table) {
            $table->bigInteger('id')->unsigned()->primary();
            $table->string('name', 64);
            $table->string('alpha_2', 2)->index();
            $table->string('alpha_3', 3);
            $table->string('dial_code', 8);
            $table->unsignedTinyInteger('order_index')->default(100);
        });

        DB::table('country')->insert(['id'=>4, 'name'=>"Afghanistan", 'alpha_2'=>"AF", 'alpha_3'=>"AFG", 'dial_code'=>"93"]);
        DB::table('country')->insert(['id'=>8, 'name'=>"Albania", 'alpha_2'=>"AL", 'alpha_3'=>"ALB", 'dial_code'=>"355"]);
        DB::table('country')->insert(['id'=>12, 'name'=>"Algeria", 'alpha_2'=>"DZ", 'alpha_3'=>"DZA", 'dial_code'=>"213"]);
        DB::table('country')->insert(['id'=>16, 'name'=>"American Samoa", 'alpha_2'=>"AS", 'alpha_3'=>"ASM", 'dial_code'=>"1684"]);
        DB::table('country')->insert(['id'=>20, 'name'=>"Andorra", 'alpha_2'=>"AD", 'alpha_3'=>"AND", 'dial_code'=>"376"]);
        DB::table('country')->insert(['id'=>24, 'name'=>"Angola", 'alpha_2'=>"AO", 'alpha_3'=>"AGO", 'dial_code'=>"244"]);
        DB::table('country')->insert(['id'=>660, 'name'=>"Anguilla", 'alpha_2'=>"AI", 'alpha_3'=>"AIA", 'dial_code'=>"1264"]);
        DB::table('country')->insert(['id'=>10, 'name'=>"Antarctica", 'alpha_2'=>"AQ", 'alpha_3'=>"ATA", 'dial_code'=>"672"]);
        DB::table('country')->insert(['id'=>28, 'name'=>"Antigua and Barbuda", 'alpha_2'=>"AG", 'alpha_3'=>"ATG", 'dial_code'=>"1268"]);
        DB::table('country')->insert(['id'=>32, 'name'=>"Argentina", 'alpha_2'=>"AR", 'alpha_3'=>"ARG", 'dial_code'=>"54"]);
        DB::table('country')->insert(['id'=>51, 'name'=>"Armenia", 'alpha_2'=>"AM", 'alpha_3'=>"ARM", 'dial_code'=>"374"]);
        DB::table('country')->insert(['id'=>533, 'name'=>"Aruba", 'alpha_2'=>"AW", 'alpha_3'=>"ABW", 'dial_code'=>"297"]);
        DB::table('country')->insert(['id'=>36, 'name'=>"Australia", 'alpha_2'=>"AU", 'alpha_3'=>"AUS", 'dial_code'=>"61"]);
        DB::table('country')->insert(['id'=>40, 'name'=>"Austria", 'alpha_2'=>"AT", 'alpha_3'=>"AUT", 'dial_code'=>"43"]);
        DB::table('country')->insert(['id'=>31, 'name'=>"Azerbaijan", 'alpha_2'=>"AZ", 'alpha_3'=>"AZE", 'dial_code'=>"994"]);
        DB::table('country')->insert(['id'=>44, 'name'=>"Bahamas", 'alpha_2'=>"BS", 'alpha_3'=>"BHS", 'dial_code'=>"1242"]);
        DB::table('country')->insert(['id'=>48, 'name'=>"Bahrain", 'alpha_2'=>"BH", 'alpha_3'=>"BHR", 'dial_code'=>"973"]);
        DB::table('country')->insert(['id'=>50, 'name'=>"Bangladesh", 'alpha_2'=>"BD", 'alpha_3'=>"BGD", 'dial_code'=>"880"]);
        DB::table('country')->insert(['id'=>52, 'name'=>"Barbados", 'alpha_2'=>"BB", 'alpha_3'=>"BRB", 'dial_code'=>"1-246"]);
        DB::table('country')->insert(['id'=>112, 'name'=>"Belarus", 'alpha_2'=>"BY", 'alpha_3'=>"BLR", 'dial_code'=>"375"]);
        DB::table('country')->insert(['id'=>56, 'name'=>"Belgium", 'alpha_2'=>"BE", 'alpha_3'=>"BEL", 'dial_code'=>"32"]);
        DB::table('country')->insert(['id'=>84, 'name'=>"Belize", 'alpha_2'=>"BZ", 'alpha_3'=>"BLZ", 'dial_code'=>"501"]);
        DB::table('country')->insert(['id'=>204, 'name'=>"Benin", 'alpha_2'=>"BJ", 'alpha_3'=>"BEN", 'dial_code'=>"229"]);
        DB::table('country')->insert(['id'=>60, 'name'=>"Bermuda", 'alpha_2'=>"BM", 'alpha_3'=>"BMU", 'dial_code'=>"1441"]);
        DB::table('country')->insert(['id'=>64, 'name'=>"Bhutan", 'alpha_2'=>"BT", 'alpha_3'=>"BTN", 'dial_code'=>"975"]);
        DB::table('country')->insert(['id'=>68, 'name'=>"Bolivia", 'alpha_2'=>"BO", 'alpha_3'=>"BOL", 'dial_code'=>"591"]);
        DB::table('country')->insert(['id'=>535, 'name'=>"Bonaire", 'alpha_2'=>"BQ", 'alpha_3'=>"BES", 'dial_code'=>"599"]);
        DB::table('country')->insert(['id'=>70, 'name'=>"Bosnia and Herzegovina", 'alpha_2'=>"BA", 'alpha_3'=>"BIH", 'dial_code'=>"387"]);
        DB::table('country')->insert(['id'=>72, 'name'=>"Botswana", 'alpha_2'=>"BW", 'alpha_3'=>"BWA", 'dial_code'=>"267"]);
        DB::table('country')->insert(['id'=>74, 'name'=>"Bouvet Island", 'alpha_2'=>"BV", 'alpha_3'=>"BVT", 'dial_code'=>"47"]);
        DB::table('country')->insert(['id'=>76, 'name'=>"Brazil", 'alpha_2'=>"BR", 'alpha_3'=>"BRA", 'dial_code'=>"55"]);
        DB::table('country')->insert(['id'=>86, 'name'=>"British Indian Ocean Territory", 'alpha_2'=>"IO", 'alpha_3'=>"IOT", 'dial_code'=>"246"]);
        DB::table('country')->insert(['id'=>96, 'name'=>"Brunei Darussalam", 'alpha_2'=>"BN", 'alpha_3'=>"BRN", 'dial_code'=>"673"]);
        DB::table('country')->insert(['id'=>100, 'name'=>"Bulgaria", 'alpha_2'=>"BG", 'alpha_3'=>"BGR", 'dial_code'=>"359"]);
        DB::table('country')->insert(['id'=>854, 'name'=>"Burkina Faso", 'alpha_2'=>"BF", 'alpha_3'=>"BFA", 'dial_code'=>"226"]);
        DB::table('country')->insert(['id'=>108, 'name'=>"Burundi", 'alpha_2'=>"BI", 'alpha_3'=>"BDI", 'dial_code'=>"257"]);
        DB::table('country')->insert(['id'=>116, 'name'=>"Cambodia", 'alpha_2'=>"KH", 'alpha_3'=>"KHM", 'dial_code'=>"855"]);
        DB::table('country')->insert(['id'=>120, 'name'=>"Cameroon", 'alpha_2'=>"CM", 'alpha_3'=>"CMR", 'dial_code'=>"237"]);
        DB::table('country')->insert(['id'=>124, 'name'=>"Canada", 'alpha_2'=>"CA", 'alpha_3'=>"CAN", 'dial_code'=>"1"]);
        DB::table('country')->insert(['id'=>132, 'name'=>"Cape Verde", 'alpha_2'=>"CV", 'alpha_3'=>"CPV", 'dial_code'=>"238"]);
        DB::table('country')->insert(['id'=>136, 'name'=>"Cayman Islands", 'alpha_2'=>"KY", 'alpha_3'=>"CYM", 'dial_code'=>"1345"]);
        DB::table('country')->insert(['id'=>140, 'name'=>"Central African Republic", 'alpha_2'=>"CF", 'alpha_3'=>"CAF", 'dial_code'=>"236"]);
        DB::table('country')->insert(['id'=>148, 'name'=>"Chad", 'alpha_2'=>"TD", 'alpha_3'=>"TCD", 'dial_code'=>"235"]);
        DB::table('country')->insert(['id'=>152, 'name'=>"Chile", 'alpha_2'=>"CL", 'alpha_3'=>"CHL", 'dial_code'=>"56"]);
        DB::table('country')->insert(['id'=>156, 'name'=>"China", 'alpha_2'=>"CN", 'alpha_3'=>"CHN", 'dial_code'=>"86"]);
        DB::table('country')->insert(['id'=>162, 'name'=>"Christmas Island", 'alpha_2'=>"CX", 'alpha_3'=>"CXR", 'dial_code'=>"61"]);
        DB::table('country')->insert(['id'=>166, 'name'=>"Cocos (Keeling) Islands", 'alpha_2'=>"CC", 'alpha_3'=>"CCK", 'dial_code'=>"61"]);
        DB::table('country')->insert(['id'=>170, 'name'=>"Colombia", 'alpha_2'=>"CO", 'alpha_3'=>"COL", 'dial_code'=>"57"]);
        DB::table('country')->insert(['id'=>174, 'name'=>"Comoros", 'alpha_2'=>"KM", 'alpha_3'=>"COM", 'dial_code'=>"269"]);
        DB::table('country')->insert(['id'=>178, 'name'=>"Congo", 'alpha_2'=>"CG", 'alpha_3'=>"COG", 'dial_code'=>"242"]);
        DB::table('country')->insert(['id'=>180, 'name'=>"Democratic Republic of the Congo", 'alpha_2'=>"CD", 'alpha_3'=>"COD", 'dial_code'=>"243"]);
        DB::table('country')->insert(['id'=>184, 'name'=>"Cook Islands", 'alpha_2'=>"CK", 'alpha_3'=>"COK", 'dial_code'=>"682"]);
        DB::table('country')->insert(['id'=>188, 'name'=>"Costa Rica", 'alpha_2'=>"CR", 'alpha_3'=>"CRI", 'dial_code'=>"506"]);
        DB::table('country')->insert(['id'=>191, 'name'=>"Croatia", 'alpha_2'=>"HR", 'alpha_3'=>"HRV", 'dial_code'=>"385"]);
        DB::table('country')->insert(['id'=>192, 'name'=>"Cuba", 'alpha_2'=>"CU", 'alpha_3'=>"CUB", 'dial_code'=>"53"]);
        DB::table('country')->insert(['id'=>531, 'name'=>"Curacao", 'alpha_2'=>"CW", 'alpha_3'=>"CUW", 'dial_code'=>"599"]);
        DB::table('country')->insert(['id'=>196, 'name'=>"Cyprus", 'alpha_2'=>"CY", 'alpha_3'=>"CYP", 'dial_code'=>"357"]);
        DB::table('country')->insert(['id'=>203, 'name'=>"Czech Republic", 'alpha_2'=>"CZ", 'alpha_3'=>"CZE", 'dial_code'=>"420"]);
        DB::table('country')->insert(['id'=>384, 'name'=>"Cote d'Ivoire", 'alpha_2'=>"CI", 'alpha_3'=>"CIV", 'dial_code'=>"225"]);
        DB::table('country')->insert(['id'=>208, 'name'=>"Denmark", 'alpha_2'=>"DK", 'alpha_3'=>"DNK", 'dial_code'=>"45"]);
        DB::table('country')->insert(['id'=>262, 'name'=>"Djibouti", 'alpha_2'=>"DJ", 'alpha_3'=>"DJI", 'dial_code'=>"253"]);
        DB::table('country')->insert(['id'=>212, 'name'=>"Dominica", 'alpha_2'=>"DM", 'alpha_3'=>"DMA", 'dial_code'=>"1767"]);
        DB::table('country')->insert(['id'=>214, 'name'=>"Dominican Republic", 'alpha_2'=>"DO", 'alpha_3'=>"DOM", 'dial_code'=>"1809"]);
        DB::table('country')->insert(['id'=>218, 'name'=>"Ecuador", 'alpha_2'=>"EC", 'alpha_3'=>"ECU", 'dial_code'=>"593"]);
        DB::table('country')->insert(['id'=>818, 'name'=>"Egypt", 'alpha_2'=>"EG", 'alpha_3'=>"EGY", 'dial_code'=>"20"]);
        DB::table('country')->insert(['id'=>222, 'name'=>"El Salvador", 'alpha_2'=>"SV", 'alpha_3'=>"SLV", 'dial_code'=>"503"]);
        DB::table('country')->insert(['id'=>226, 'name'=>"Equatorial Guinea", 'alpha_2'=>"GQ", 'alpha_3'=>"GNQ", 'dial_code'=>"240"]);
        DB::table('country')->insert(['id'=>232, 'name'=>"Eritrea", 'alpha_2'=>"ER", 'alpha_3'=>"ERI", 'dial_code'=>"291"]);
        DB::table('country')->insert(['id'=>233, 'name'=>"Estonia", 'alpha_2'=>"EE", 'alpha_3'=>"EST", 'dial_code'=>"372"]);
        DB::table('country')->insert(['id'=>231, 'name'=>"Ethiopia", 'alpha_2'=>"ET", 'alpha_3'=>"ETH", 'dial_code'=>"251"]);
        DB::table('country')->insert(['id'=>238, 'name'=>"Falkland Islands (Malvinas)", 'alpha_2'=>"FK", 'alpha_3'=>"FLK", 'dial_code'=>"500"]);
        DB::table('country')->insert(['id'=>234, 'name'=>"Faroe Islands", 'alpha_2'=>"FO", 'alpha_3'=>"FRO", 'dial_code'=>"298"]);
        DB::table('country')->insert(['id'=>242, 'name'=>"Fiji", 'alpha_2'=>"FJ", 'alpha_3'=>"FJI", 'dial_code'=>"679"]);
        DB::table('country')->insert(['id'=>246, 'name'=>"Finland", 'alpha_2'=>"FI", 'alpha_3'=>"FIN", 'dial_code'=>"358"]);
        DB::table('country')->insert(['id'=>250, 'name'=>"France", 'alpha_2'=>"FR", 'alpha_3'=>"FRA", 'dial_code'=>"33"]);
        DB::table('country')->insert(['id'=>254, 'name'=>"French Guiana", 'alpha_2'=>"GF", 'alpha_3'=>"GUF", 'dial_code'=>"594"]);
        DB::table('country')->insert(['id'=>258, 'name'=>"French Polynesia", 'alpha_2'=>"PF", 'alpha_3'=>"PYF", 'dial_code'=>"689"]);
        DB::table('country')->insert(['id'=>260, 'name'=>"French Southern Territories", 'alpha_2'=>"TF", 'alpha_3'=>"ATF", 'dial_code'=>"262"]);
        DB::table('country')->insert(['id'=>266, 'name'=>"Gabon", 'alpha_2'=>"GA", 'alpha_3'=>"GAB", 'dial_code'=>"241"]);
        DB::table('country')->insert(['id'=>270, 'name'=>"Gambia", 'alpha_2'=>"GM", 'alpha_3'=>"GMB", 'dial_code'=>"220"]);
        DB::table('country')->insert(['id'=>268, 'name'=>"Georgia", 'alpha_2'=>"GE", 'alpha_3'=>"GEO", 'dial_code'=>"995"]);
        DB::table('country')->insert(['id'=>276, 'name'=>"Germany", 'alpha_2'=>"DE", 'alpha_3'=>"DEU", 'dial_code'=>"49"]);
        DB::table('country')->insert(['id'=>288, 'name'=>"Ghana", 'alpha_2'=>"GH", 'alpha_3'=>"GHA", 'dial_code'=>"233"]);
        DB::table('country')->insert(['id'=>292, 'name'=>"Gibraltar", 'alpha_2'=>"GI", 'alpha_3'=>"GIB", 'dial_code'=>"350"]);
        DB::table('country')->insert(['id'=>300, 'name'=>"Greece", 'alpha_2'=>"GR", 'alpha_3'=>"GRC", 'dial_code'=>"30"]);
        DB::table('country')->insert(['id'=>304, 'name'=>"Greenland", 'alpha_2'=>"GL", 'alpha_3'=>"GRL", 'dial_code'=>"299"]);
        DB::table('country')->insert(['id'=>308, 'name'=>"Grenada", 'alpha_2'=>"GD", 'alpha_3'=>"GRD", 'dial_code'=>"1473"]);
        DB::table('country')->insert(['id'=>312, 'name'=>"Guadeloupe", 'alpha_2'=>"GP", 'alpha_3'=>"GLP", 'dial_code'=>"590"]);
        DB::table('country')->insert(['id'=>316, 'name'=>"Guam", 'alpha_2'=>"GU", 'alpha_3'=>"GUM", 'dial_code'=>"1671"]);
        DB::table('country')->insert(['id'=>320, 'name'=>"Guatemala", 'alpha_2'=>"GT", 'alpha_3'=>"GTM", 'dial_code'=>"502"]);
        DB::table('country')->insert(['id'=>831, 'name'=>"Guernsey", 'alpha_2'=>"GG", 'alpha_3'=>"GGY", 'dial_code'=>"44"]);
        DB::table('country')->insert(['id'=>324, 'name'=>"Guinea", 'alpha_2'=>"GN", 'alpha_3'=>"GIN", 'dial_code'=>"224"]);
        DB::table('country')->insert(['id'=>624, 'name'=>"Guinea-Bissau", 'alpha_2'=>"GW", 'alpha_3'=>"GNB", 'dial_code'=>"245"]);
        DB::table('country')->insert(['id'=>328, 'name'=>"Guyana", 'alpha_2'=>"GY", 'alpha_3'=>"GUY", 'dial_code'=>"592"]);
        DB::table('country')->insert(['id'=>332, 'name'=>"Haiti", 'alpha_2'=>"HT", 'alpha_3'=>"HTI", 'dial_code'=>"509"]);
        DB::table('country')->insert(['id'=>334, 'name'=>"Heard Island and McDonald Islands", 'alpha_2'=>"HM", 'alpha_3'=>"HMD", 'dial_code'=>"672"]);
        DB::table('country')->insert(['id'=>336, 'name'=>"Holy See (Vatican City State)", 'alpha_2'=>"VA", 'alpha_3'=>"VAT", 'dial_code'=>"379"]);
        DB::table('country')->insert(['id'=>340, 'name'=>"Honduras", 'alpha_2'=>"HN", 'alpha_3'=>"HND", 'dial_code'=>"504"]);
        DB::table('country')->insert(['id'=>344, 'name'=>"Hong Kong", 'alpha_2'=>"HK", 'alpha_3'=>"HKG", 'dial_code'=>"852"]);
        DB::table('country')->insert(['id'=>348, 'name'=>"Hungary", 'alpha_2'=>"HU", 'alpha_3'=>"HUN", 'dial_code'=>"36"]);
        DB::table('country')->insert(['id'=>352, 'name'=>"Iceland", 'alpha_2'=>"IS", 'alpha_3'=>"ISL", 'dial_code'=>"354"]);
        DB::table('country')->insert(['id'=>356, 'name'=>"India", 'alpha_2'=>"IN", 'alpha_3'=>"IND", 'dial_code'=>"91"]);
        DB::table('country')->insert(['id'=>360, 'name'=>"Indonesia", 'alpha_2'=>"ID", 'alpha_3'=>"IDN", 'dial_code'=>"62"]);
        DB::table('country')->insert(['id'=>364, 'name'=>"Iran, Islamic Republic of", 'alpha_2'=>"IR", 'alpha_3'=>"IRN", 'dial_code'=>"98"]);
        DB::table('country')->insert(['id'=>368, 'name'=>"Iraq", 'alpha_2'=>"IQ", 'alpha_3'=>"IRQ", 'dial_code'=>"964"]);
        DB::table('country')->insert(['id'=>372, 'name'=>"Ireland", 'alpha_2'=>"IE", 'alpha_3'=>"IRL", 'dial_code'=>"353"]);
        DB::table('country')->insert(['id'=>833, 'name'=>"Isle of Man", 'alpha_2'=>"IM", 'alpha_3'=>"IMN", 'dial_code'=>"44"]);
        DB::table('country')->insert(['id'=>376, 'name'=>"Israel", 'alpha_2'=>"IL", 'alpha_3'=>"ISR", 'dial_code'=>"972"]);
        DB::table('country')->insert(['id'=>380, 'name'=>"Italy", 'alpha_2'=>"IT", 'alpha_3'=>"ITA", 'dial_code'=>"39"]);
        DB::table('country')->insert(['id'=>388, 'name'=>"Jamaica", 'alpha_2'=>"JM", 'alpha_3'=>"JAM", 'dial_code'=>"1876"]);
        DB::table('country')->insert(['id'=>392, 'name'=>"Japan", 'alpha_2'=>"JP", 'alpha_3'=>"JPN", 'dial_code'=>"81"]);
        DB::table('country')->insert(['id'=>832, 'name'=>"Jersey", 'alpha_2'=>"JE", 'alpha_3'=>"JEY", 'dial_code'=>"44"]);
        DB::table('country')->insert(['id'=>400, 'name'=>"Jordan", 'alpha_2'=>"JO", 'alpha_3'=>"JOR", 'dial_code'=>"962"]);
        DB::table('country')->insert(['id'=>398, 'name'=>"Kazakhstan", 'alpha_2'=>"KZ", 'alpha_3'=>"KAZ", 'dial_code'=>"7"]);
        DB::table('country')->insert(['id'=>404, 'name'=>"Kenya", 'alpha_2'=>"KE", 'alpha_3'=>"KEN", 'dial_code'=>"254"]);
        DB::table('country')->insert(['id'=>296, 'name'=>"Kiribati", 'alpha_2'=>"KI", 'alpha_3'=>"KIR", 'dial_code'=>"686"]);
        DB::table('country')->insert(['id'=>408, 'name'=>"Korea, Democratic People's Republic of", 'alpha_2'=>"KP", 'alpha_3'=>"PRK", 'dial_code'=>"850"]);
        DB::table('country')->insert(['id'=>410, 'name'=>"Korea, Republic of", 'alpha_2'=>"KR", 'alpha_3'=>"KOR", 'dial_code'=>"82"]);
        DB::table('country')->insert(['id'=>414, 'name'=>"Kuwait", 'alpha_2'=>"KW", 'alpha_3'=>"KWT", 'dial_code'=>"965"]);
        DB::table('country')->insert(['id'=>417, 'name'=>"Kyrgyzstan", 'alpha_2'=>"KG", 'alpha_3'=>"KGZ", 'dial_code'=>"996"]);
        DB::table('country')->insert(['id'=>418, 'name'=>"Lao People's Democratic Republic", 'alpha_2'=>"LA", 'alpha_3'=>"LAO", 'dial_code'=>"856"]);
        DB::table('country')->insert(['id'=>428, 'name'=>"Latvia", 'alpha_2'=>"LV", 'alpha_3'=>"LVA", 'dial_code'=>"371"]);
        DB::table('country')->insert(['id'=>422, 'name'=>"Lebanon", 'alpha_2'=>"LB", 'alpha_3'=>"LBN", 'dial_code'=>"961"]);
        DB::table('country')->insert(['id'=>426, 'name'=>"Lesotho", 'alpha_2'=>"LS", 'alpha_3'=>"LSO", 'dial_code'=>"266"]);
        DB::table('country')->insert(['id'=>430, 'name'=>"Liberia", 'alpha_2'=>"LR", 'alpha_3'=>"LBR", 'dial_code'=>"231"]);
        DB::table('country')->insert(['id'=>434, 'name'=>"Libya", 'alpha_2'=>"LY", 'alpha_3'=>"LBY", 'dial_code'=>"218"]);
        DB::table('country')->insert(['id'=>438, 'name'=>"Liechtenstein", 'alpha_2'=>"LI", 'alpha_3'=>"LIE", 'dial_code'=>"423"]);
        DB::table('country')->insert(['id'=>440, 'name'=>"Lithuania", 'alpha_2'=>"LT", 'alpha_3'=>"LTU", 'dial_code'=>"370"]);
        DB::table('country')->insert(['id'=>442, 'name'=>"Luxembourg", 'alpha_2'=>"LU", 'alpha_3'=>"LUX", 'dial_code'=>"352"]);
        DB::table('country')->insert(['id'=>446, 'name'=>"Macao", 'alpha_2'=>"MO", 'alpha_3'=>"MAC", 'dial_code'=>"853"]);
        DB::table('country')->insert(['id'=>807, 'name'=>"Macedonia, the Former Yugoslav Republic of", 'alpha_2'=>"MK", 'alpha_3'=>"MKD", 'dial_code'=>"389"]);
        DB::table('country')->insert(['id'=>450, 'name'=>"Madagascar", 'alpha_2'=>"MG", 'alpha_3'=>"MDG", 'dial_code'=>"261"]);
        DB::table('country')->insert(['id'=>454, 'name'=>"Malawi", 'alpha_2'=>"MW", 'alpha_3'=>"MWI", 'dial_code'=>"265"]);
        DB::table('country')->insert(['id'=>458, 'name'=>"Malaysia", 'alpha_2'=>"MY", 'alpha_3'=>"MYS", 'dial_code'=>"60"]);
        DB::table('country')->insert(['id'=>462, 'name'=>"Maldives", 'alpha_2'=>"MV", 'alpha_3'=>"MDV", 'dial_code'=>"960"]);
        DB::table('country')->insert(['id'=>466, 'name'=>"Mali", 'alpha_2'=>"ML", 'alpha_3'=>"MLI", 'dial_code'=>"223"]);
        DB::table('country')->insert(['id'=>470, 'name'=>"Malta", 'alpha_2'=>"MT", 'alpha_3'=>"MLT", 'dial_code'=>"356"]);
        DB::table('country')->insert(['id'=>584, 'name'=>"Marshall Islands", 'alpha_2'=>"MH", 'alpha_3'=>"MHL", 'dial_code'=>"692"]);
        DB::table('country')->insert(['id'=>474, 'name'=>"Martinique", 'alpha_2'=>"MQ", 'alpha_3'=>"MTQ", 'dial_code'=>"596"]);
        DB::table('country')->insert(['id'=>478, 'name'=>"Mauritania", 'alpha_2'=>"MR", 'alpha_3'=>"MRT", 'dial_code'=>"222"]);
        DB::table('country')->insert(['id'=>480, 'name'=>"Mauritius", 'alpha_2'=>"MU", 'alpha_3'=>"MUS", 'dial_code'=>"230"]);
        DB::table('country')->insert(['id'=>175, 'name'=>"Mayotte", 'alpha_2'=>"YT", 'alpha_3'=>"MYT", 'dial_code'=>"262"]);
        DB::table('country')->insert(['id'=>484, 'name'=>"Mexico", 'alpha_2'=>"MX", 'alpha_3'=>"MEX", 'dial_code'=>"52"]);
        DB::table('country')->insert(['id'=>583, 'name'=>"Micronesia, Federated States of", 'alpha_2'=>"FM", 'alpha_3'=>"FSM", 'dial_code'=>"691"]);
        DB::table('country')->insert(['id'=>498, 'name'=>"Moldova, Republic of", 'alpha_2'=>"MD", 'alpha_3'=>"MDA", 'dial_code'=>"373"]);
        DB::table('country')->insert(['id'=>492, 'name'=>"Monaco", 'alpha_2'=>"MC", 'alpha_3'=>"MCO", 'dial_code'=>"377"]);
        DB::table('country')->insert(['id'=>496, 'name'=>"Mongolia", 'alpha_2'=>"MN", 'alpha_3'=>"MNG", 'dial_code'=>"976"]);
        DB::table('country')->insert(['id'=>499, 'name'=>"Montenegro", 'alpha_2'=>"ME", 'alpha_3'=>"MNE", 'dial_code'=>"382"]);
        DB::table('country')->insert(['id'=>500, 'name'=>"Montserrat", 'alpha_2'=>"MS", 'alpha_3'=>"MSR", 'dial_code'=>"1664"]);
        DB::table('country')->insert(['id'=>504, 'name'=>"Morocco", 'alpha_2'=>"MA", 'alpha_3'=>"MAR", 'dial_code'=>"212"]);
        DB::table('country')->insert(['id'=>508, 'name'=>"Mozambique", 'alpha_2'=>"MZ", 'alpha_3'=>"MOZ", 'dial_code'=>"258"]);
        DB::table('country')->insert(['id'=>104, 'name'=>"Myanmar", 'alpha_2'=>"MM", 'alpha_3'=>"MMR", 'dial_code'=>"95"]);
        DB::table('country')->insert(['id'=>516, 'name'=>"Namibia", 'alpha_2'=>"NA", 'alpha_3'=>"NAM", 'dial_code'=>"264"]);
        DB::table('country')->insert(['id'=>520, 'name'=>"Nauru", 'alpha_2'=>"NR", 'alpha_3'=>"NRU", 'dial_code'=>"674"]);
        DB::table('country')->insert(['id'=>524, 'name'=>"Nepal", 'alpha_2'=>"NP", 'alpha_3'=>"NPL", 'dial_code'=>"977"]);
        DB::table('country')->insert(['id'=>528, 'name'=>"Netherlands", 'alpha_2'=>"NL", 'alpha_3'=>"NLD", 'dial_code'=>"31"]);
        DB::table('country')->insert(['id'=>540, 'name'=>"New Caledonia", 'alpha_2'=>"NC", 'alpha_3'=>"NCL", 'dial_code'=>"687"]);
        DB::table('country')->insert(['id'=>554, 'name'=>"New Zealand", 'alpha_2'=>"NZ", 'alpha_3'=>"NZL", 'dial_code'=>"64"]);
        DB::table('country')->insert(['id'=>558, 'name'=>"Nicaragua", 'alpha_2'=>"NI", 'alpha_3'=>"NIC", 'dial_code'=>"505"]);
        DB::table('country')->insert(['id'=>562, 'name'=>"Niger", 'alpha_2'=>"NE", 'alpha_3'=>"NER", 'dial_code'=>"227"]);
        DB::table('country')->insert(['id'=>566, 'name'=>"Nigeria", 'alpha_2'=>"NG", 'alpha_3'=>"NGA", 'dial_code'=>"234"]);
        DB::table('country')->insert(['id'=>570, 'name'=>"Niue", 'alpha_2'=>"NU", 'alpha_3'=>"NIU", 'dial_code'=>"683"]);
        DB::table('country')->insert(['id'=>574, 'name'=>"Norfolk Island", 'alpha_2'=>"NF", 'alpha_3'=>"NFK", 'dial_code'=>"672"]);
        DB::table('country')->insert(['id'=>580, 'name'=>"Northern Mariana Islands", 'alpha_2'=>"MP", 'alpha_3'=>"MNP", 'dial_code'=>"1670"]);
        DB::table('country')->insert(['id'=>578, 'name'=>"Norway", 'alpha_2'=>"NO", 'alpha_3'=>"NOR", 'dial_code'=>"47"]);
        DB::table('country')->insert(['id'=>512, 'name'=>"Oman", 'alpha_2'=>"OM", 'alpha_3'=>"OMN", 'dial_code'=>"968"]);
        DB::table('country')->insert(['id'=>586, 'name'=>"Pakistan", 'alpha_2'=>"PK", 'alpha_3'=>"PAK", 'dial_code'=>"92"]);
        DB::table('country')->insert(['id'=>585, 'name'=>"Palau", 'alpha_2'=>"PW", 'alpha_3'=>"PLW", 'dial_code'=>"680"]);
        DB::table('country')->insert(['id'=>275, 'name'=>"Palestine, State of", 'alpha_2'=>"PS", 'alpha_3'=>"PSE", 'dial_code'=>"970"]);
        DB::table('country')->insert(['id'=>591, 'name'=>"Panama", 'alpha_2'=>"PA", 'alpha_3'=>"PAN", 'dial_code'=>"507"]);
        DB::table('country')->insert(['id'=>598, 'name'=>"Papua New Guinea", 'alpha_2'=>"PG", 'alpha_3'=>"PNG", 'dial_code'=>"675"]);
        DB::table('country')->insert(['id'=>600, 'name'=>"Paraguay", 'alpha_2'=>"PY", 'alpha_3'=>"PRY", 'dial_code'=>"595"]);
        DB::table('country')->insert(['id'=>604, 'name'=>"Peru", 'alpha_2'=>"PE", 'alpha_3'=>"PER", 'dial_code'=>"51"]);
        DB::table('country')->insert(['id'=>608, 'name'=>"Philippines", 'alpha_2'=>"PH", 'alpha_3'=>"PHL", 'dial_code'=>"63"]);
        DB::table('country')->insert(['id'=>612, 'name'=>"Pitcairn", 'alpha_2'=>"PN", 'alpha_3'=>"PCN", 'dial_code'=>"870"]);
        DB::table('country')->insert(['id'=>616, 'name'=>"Poland", 'alpha_2'=>"PL", 'alpha_3'=>"POL", 'dial_code'=>"48"]);
        DB::table('country')->insert(['id'=>620, 'name'=>"Portugal", 'alpha_2'=>"PT", 'alpha_3'=>"PRT", 'dial_code'=>"351"]);
        DB::table('country')->insert(['id'=>630, 'name'=>"Puerto Rico", 'alpha_2'=>"PR", 'alpha_3'=>"PRI", 'dial_code'=>"1"]);
        DB::table('country')->insert(['id'=>634, 'name'=>"Qatar", 'alpha_2'=>"QA", 'alpha_3'=>"QAT", 'dial_code'=>"974"]);
        DB::table('country')->insert(['id'=>642, 'name'=>"Romania", 'alpha_2'=>"RO", 'alpha_3'=>"ROU", 'dial_code'=>"40"]);
        DB::table('country')->insert(['id'=>643, 'name'=>"Russian Federation", 'alpha_2'=>"RU", 'alpha_3'=>"RUS", 'dial_code'=>"7"]);
        DB::table('country')->insert(['id'=>646, 'name'=>"Rwanda", 'alpha_2'=>"RW", 'alpha_3'=>"RWA", 'dial_code'=>"250"]);
        DB::table('country')->insert(['id'=>638, 'name'=>"Reunion", 'alpha_2'=>"RE", 'alpha_3'=>"REU", 'dial_code'=>"262"]);
        DB::table('country')->insert(['id'=>652, 'name'=>"Saint Barthelemy", 'alpha_2'=>"BL", 'alpha_3'=>"BLM", 'dial_code'=>"590"]);
        DB::table('country')->insert(['id'=>654, 'name'=>"Saint Helena", 'alpha_2'=>"SH", 'alpha_3'=>"SHN", 'dial_code'=>"290"]);
        DB::table('country')->insert(['id'=>659, 'name'=>"Saint Kitts and Nevis", 'alpha_2'=>"KN", 'alpha_3'=>"KNA", 'dial_code'=>"1869"]);
        DB::table('country')->insert(['id'=>662, 'name'=>"Saint Lucia", 'alpha_2'=>"LC", 'alpha_3'=>"LCA", 'dial_code'=>"1758"]);
        DB::table('country')->insert(['id'=>663, 'name'=>"Saint Martin (French part)", 'alpha_2'=>"MF", 'alpha_3'=>"MAF", 'dial_code'=>"590"]);
        DB::table('country')->insert(['id'=>666, 'name'=>"Saint Pierre and Miquelon", 'alpha_2'=>"PM", 'alpha_3'=>"SPM", 'dial_code'=>"508"]);
        DB::table('country')->insert(['id'=>670, 'name'=>"Saint Vincent and the Grenadines", 'alpha_2'=>"VC", 'alpha_3'=>"VCT", 'dial_code'=>"1784"]);
        DB::table('country')->insert(['id'=>882, 'name'=>"Samoa", 'alpha_2'=>"WS", 'alpha_3'=>"WSM", 'dial_code'=>"685"]);
        DB::table('country')->insert(['id'=>674, 'name'=>"San Marino", 'alpha_2'=>"SM", 'alpha_3'=>"SMR", 'dial_code'=>"378"]);
        DB::table('country')->insert(['id'=>678, 'name'=>"Sao Tome and Principe", 'alpha_2'=>"ST", 'alpha_3'=>"STP", 'dial_code'=>"239"]);
        DB::table('country')->insert(['id'=>682, 'name'=>"Saudi Arabia", 'alpha_2'=>"SA", 'alpha_3'=>"SAU", 'dial_code'=>"966"]);
        DB::table('country')->insert(['id'=>686, 'name'=>"Senegal", 'alpha_2'=>"SN", 'alpha_3'=>"SEN", 'dial_code'=>"221"]);
        DB::table('country')->insert(['id'=>688, 'name'=>"Serbia", 'alpha_2'=>"RS", 'alpha_3'=>"SRB", 'dial_code'=>"381"]);
        DB::table('country')->insert(['id'=>690, 'name'=>"Seychelles", 'alpha_2'=>"SC", 'alpha_3'=>"SYC", 'dial_code'=>"248"]);
        DB::table('country')->insert(['id'=>694, 'name'=>"Sierra Leone", 'alpha_2'=>"SL", 'alpha_3'=>"SLE", 'dial_code'=>"232"]);
        DB::table('country')->insert(['id'=>702, 'name'=>"Singapore", 'alpha_2'=>"SG", 'alpha_3'=>"SGP", 'dial_code'=>"65"]);
        DB::table('country')->insert(['id'=>534, 'name'=>"Sint Maarten (Dutch part)", 'alpha_2'=>"SX", 'alpha_3'=>"SXM", 'dial_code'=>"1721"]);
        DB::table('country')->insert(['id'=>703, 'name'=>"Slovakia", 'alpha_2'=>"SK", 'alpha_3'=>"SVK", 'dial_code'=>"421"]);
        DB::table('country')->insert(['id'=>705, 'name'=>"Slovenia", 'alpha_2'=>"SI", 'alpha_3'=>"SVN", 'dial_code'=>"386"]);
        DB::table('country')->insert(['id'=>90, 'name'=>"Solomon Islands", 'alpha_2'=>"SB", 'alpha_3'=>"SLB", 'dial_code'=>"677"]);
        DB::table('country')->insert(['id'=>706, 'name'=>"Somalia", 'alpha_2'=>"SO", 'alpha_3'=>"SOM", 'dial_code'=>"252"]);
        DB::table('country')->insert(['id'=>710, 'name'=>"South Africa", 'alpha_2'=>"ZA", 'alpha_3'=>"ZAF", 'dial_code'=>"27"]);
        DB::table('country')->insert(['id'=>239, 'name'=>"South Georgia and the South Sandwich Islands", 'alpha_2'=>"GS", 'alpha_3'=>"SGS", 'dial_code'=>"500"]);
        DB::table('country')->insert(['id'=>728, 'name'=>"South Sudan", 'alpha_2'=>"SS", 'alpha_3'=>"SSD", 'dial_code'=>"211"]);
        DB::table('country')->insert(['id'=>724, 'name'=>"Spain", 'alpha_2'=>"ES", 'alpha_3'=>"ESP", 'dial_code'=>"34"]);
        DB::table('country')->insert(['id'=>144, 'name'=>"Sri Lanka", 'alpha_2'=>"LK", 'alpha_3'=>"LKA", 'dial_code'=>"94"]);
        DB::table('country')->insert(['id'=>729, 'name'=>"Sudan", 'alpha_2'=>"SD", 'alpha_3'=>"SDN", 'dial_code'=>"249"]);
        DB::table('country')->insert(['id'=>740, 'name'=>"Suriname", 'alpha_2'=>"SR", 'alpha_3'=>"SUR", 'dial_code'=>"597"]);
        DB::table('country')->insert(['id'=>744, 'name'=>"Svalbard and Jan Mayen", 'alpha_2'=>"SJ", 'alpha_3'=>"SJM", 'dial_code'=>"47"]);
        DB::table('country')->insert(['id'=>748, 'name'=>"Swaziland", 'alpha_2'=>"SZ", 'alpha_3'=>"SWZ", 'dial_code'=>"268"]);
        DB::table('country')->insert(['id'=>752, 'name'=>"Sweden", 'alpha_2'=>"SE", 'alpha_3'=>"SWE", 'dial_code'=>"46"]);
        DB::table('country')->insert(['id'=>756, 'name'=>"Switzerland", 'alpha_2'=>"CH", 'alpha_3'=>"CHE", 'dial_code'=>"41"]);
        DB::table('country')->insert(['id'=>760, 'name'=>"Syrian Arab Republic", 'alpha_2'=>"SY", 'alpha_3'=>"SYR", 'dial_code'=>"963"]);
        DB::table('country')->insert(['id'=>158, 'name'=>"Taiwan", 'alpha_2'=>"TW", 'alpha_3'=>"TWN", 'dial_code'=>"886"]);
        DB::table('country')->insert(['id'=>762, 'name'=>"Tajikistan", 'alpha_2'=>"TJ", 'alpha_3'=>"TJK", 'dial_code'=>"992"]);
        DB::table('country')->insert(['id'=>834, 'name'=>"United Republic of Tanzania", 'alpha_2'=>"TZ", 'alpha_3'=>"TZA", 'dial_code'=>"255"]);
        DB::table('country')->insert(['id'=>764, 'name'=>"Thailand", 'alpha_2'=>"TH", 'alpha_3'=>"THA", 'dial_code'=>"66"]);
        DB::table('country')->insert(['id'=>626, 'name'=>"Timor-Leste", 'alpha_2'=>"TL", 'alpha_3'=>"TLS", 'dial_code'=>"670"]);
        DB::table('country')->insert(['id'=>768, 'name'=>"Togo", 'alpha_2'=>"TG", 'alpha_3'=>"TGO", 'dial_code'=>"228"]);
        DB::table('country')->insert(['id'=>772, 'name'=>"Tokelau", 'alpha_2'=>"TK", 'alpha_3'=>"TKL", 'dial_code'=>"690"]);
        DB::table('country')->insert(['id'=>776, 'name'=>"Tonga", 'alpha_2'=>"TO", 'alpha_3'=>"TON", 'dial_code'=>"676"]);
        DB::table('country')->insert(['id'=>780, 'name'=>"Trinidad and Tobago", 'alpha_2'=>"TT", 'alpha_3'=>"TTO", 'dial_code'=>"1868"]);
        DB::table('country')->insert(['id'=>788, 'name'=>"Tunisia", 'alpha_2'=>"TN", 'alpha_3'=>"TUN", 'dial_code'=>"216"]);
        DB::table('country')->insert(['id'=>792, 'name'=>"Turkey", 'alpha_2'=>"TR", 'alpha_3'=>"TUR", 'dial_code'=>"90"]);
        DB::table('country')->insert(['id'=>795, 'name'=>"Turkmenistan", 'alpha_2'=>"TM", 'alpha_3'=>"TKM", 'dial_code'=>"993"]);
        DB::table('country')->insert(['id'=>796, 'name'=>"Turks and Caicos Islands", 'alpha_2'=>"TC", 'alpha_3'=>"TCA", 'dial_code'=>"1649"]);
        DB::table('country')->insert(['id'=>798, 'name'=>"Tuvalu", 'alpha_2'=>"TV", 'alpha_3'=>"TUV", 'dial_code'=>"688"]);
        DB::table('country')->insert(['id'=>800, 'name'=>"Uganda", 'alpha_2'=>"UG", 'alpha_3'=>"UGA", 'dial_code'=>"256"]);
        DB::table('country')->insert(['id'=>804, 'name'=>"Ukraine", 'alpha_2'=>"UA", 'alpha_3'=>"UKR", 'dial_code'=>"380"]);
        DB::table('country')->insert(['id'=>784, 'name'=>"United Arab Emirates", 'alpha_2'=>"AE", 'alpha_3'=>"ARE", 'dial_code'=>"971"]);
        DB::table('country')->insert(['id'=>826, 'name'=>"United Kingdom", 'alpha_2'=>"GB", 'alpha_3'=>"GBR", 'dial_code'=>"44", 'order_index'=>1]);
        DB::table('country')->insert(['id'=>840, 'name'=>"United States", 'alpha_2'=>"US", 'alpha_3'=>"USA", 'dial_code'=>"1", 'order_index'=>2]);
        DB::table('country')->insert(['id'=>581, 'name'=>"United States Minor Outlying Islands", 'alpha_2'=>"UM", 'alpha_3'=>"UMI", 'dial_code'=>"1"]);
        DB::table('country')->insert(['id'=>858, 'name'=>"Uruguay", 'alpha_2'=>"UY", 'alpha_3'=>"URY", 'dial_code'=>"598"]);
        DB::table('country')->insert(['id'=>860, 'name'=>"Uzbekistan", 'alpha_2'=>"UZ", 'alpha_3'=>"UZB", 'dial_code'=>"998"]);
        DB::table('country')->insert(['id'=>548, 'name'=>"Vanuatu", 'alpha_2'=>"VU", 'alpha_3'=>"VUT", 'dial_code'=>"678"]);
        DB::table('country')->insert(['id'=>862, 'name'=>"Venezuela", 'alpha_2'=>"VE", 'alpha_3'=>"VEN", 'dial_code'=>"58"]);
        DB::table('country')->insert(['id'=>704, 'name'=>"Viet Nam", 'alpha_2'=>"VN", 'alpha_3'=>"VNM", 'dial_code'=>"84"]);
        DB::table('country')->insert(['id'=>92, 'name'=>"British Virgin Islands", 'alpha_2'=>"VG", 'alpha_3'=>"VGB", 'dial_code'=>"1284"]);
        DB::table('country')->insert(['id'=>850, 'name'=>"US Virgin Islands", 'alpha_2'=>"VI", 'alpha_3'=>"VIR", 'dial_code'=>"1340"]);
        DB::table('country')->insert(['id'=>876, 'name'=>"Wallis and Futuna", 'alpha_2'=>"WF", 'alpha_3'=>"WLF", 'dial_code'=>"681"]);
        DB::table('country')->insert(['id'=>732, 'name'=>"Western Sahara", 'alpha_2'=>"EH", 'alpha_3'=>"ESH", 'dial_code'=>"212"]);
        DB::table('country')->insert(['id'=>887, 'name'=>"Yemen", 'alpha_2'=>"YE", 'alpha_3'=>"YEM", 'dial_code'=>"967"]);
        DB::table('country')->insert(['id'=>894, 'name'=>"Zambia", 'alpha_2'=>"ZM", 'alpha_3'=>"ZMB", 'dial_code'=>"260"]);
        DB::table('country')->insert(['id'=>716, 'name'=>"Zimbabwe", 'alpha_2'=>"ZW", 'alpha_3'=>"ZWE", 'dial_code'=>"263"]);
    }

    public function down(): void
    {
        Schema::disableForeignKeyConstraints();
        Schema::dropIfExists('country');
        Schema::enableForeignKeyConstraints();
    }
};
